src/main/java/com/daengdaeng_eodiga/project/Global/enums/ErrorCode.java
src/main/java/com/daengdaeng_eodiga/project/Global/exception/DateNotFoundException.java
src/main/java/com/daengdaeng_eodiga/project/Global/exception/PetNotFoundException.java
src/main/java/com/daengdaeng_eodiga/project/Global/exception/UserUnauthorizedException.java
src/main/java/com/daengdaeng_eodiga/project/pet/controller/PetController.java
src/main/java/com/daengdaeng_eodiga/project/pet/dto/PetDetailResponseDto.java
src/main/java/com/daengdaeng_eodiga/project/pet/dto/PetListResponseDto.java
src/main/java/com/daengdaeng_eodiga/project/pet/dto/PetRegisterDto.java
src/main/java/com/daengdaeng_eodiga/project/pet/dto/PetUpdateDto.java
src/main/java/com/daengdaeng_eodiga/project/pet/entity/Pet.java
src/main/java/com/daengdaeng_eodiga/project/pet/service/PetService.java
src/main/java/com/daengdaeng_eodiga/project/user/entity/User.java

> 반려동물 등록 구현
> 반려동물 수정 구현
> 반려동물 삭제 구현
> 반려동물 목록조회 구현
> 반려동물 상세조회 구현
- 등록
- 목록조회
- 상세조회
> 정상 response
> ![image](https://github.com/user-attachments/assets/4cfbd532-99cb-4384-9197-33473f9e67b0)
>
> 예외 (반려견이 존재하지 않을 경우)
- 임시로 userId 를 하드코딩으로 1이라고 지정해뒀는데, 이 부분도 추후에 변경할 예정입니다.
개선해야할 점 등 편하게 말씀해주세요!

Feat/pet: 반려동물 API 구현

---

src/main/java/com/daengdaeng_eodiga/project/favorite/controller/FavoriteController.java
src/main/java/com/daengdaeng_eodiga/project/pet/controller/PetController.java
src/main/java/com/daengdaeng_eodiga/project/review/controller/ReviewController.java
src/main/java/com/daengdaeng_eodiga/project/visit/controller/VisitController.java
src/main/resources/application.yml

- Controller에서 AuthenticationPrincipal에 있는 유저를 조회해 서비스에 전달

Refactor/login connect : 컨트롤러 유저 주입

---

src/main/resources/application.yml

Refactor/login connect : DB 연결 관련 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java

security 내세어 cookies 조건문 분기를 수정하였습니다.

refactor/security  : cookies 조건문 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java

Refactor/security : security 로깅 추가

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java

프론트 테스트 동안에만 security http, secure 제거합니다.

Refactor/security : security http, secure 제거

---

.github/workflows/deploy.yml

프론트 테스트 동안에만 security http, secure 제거합니다.

V1 : 즐겨찾기 response DTO 반환값 수정 및 쿠키 secure 수정

---

src/main/java/com/daengdaeng_eodiga/project/common/service/CommonCodeService.java
src/main/java/com/daengdaeng_eodiga/project/pet/controller/PetController.java
src/main/java/com/daengdaeng_eodiga/project/pet/service/PetService.java

> Pet 서비스에 있던 공통코드 레포지토리 코드를 공통코드 서비스에 분리했습니다.

refactor: Pet 서비스에 있던 공통코드 레포지토리 분리

---

src/main/resources/application.yml

refator:yml 파일 oauth url 수정

---

src/main/java/com/daengdaeng_eodiga/project/pet/controller/PetController.java
src/main/java/com/daengdaeng_eodiga/project/pet/dto/PetUpdateDto.java
src/main/java/com/daengdaeng_eodiga/project/pet/service/PetService.java

> 변경 전 : 반려동물 정보 수정 시, petId를 requestBody에 전달
> 변경 후 : petId는 url에 전달하도록 변경
> ![image](https://github.com/user-attachments/assets/fdeaf800-b645-482b-984c-f5d34dafb873)

refactor: 반려동물 정보 수정 시, petId는 url에 전달하도록 변경

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomOAuth2UserService.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/dto/KakaoResponse.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/OauthUserService.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/TokenService.java

Refator/jwt: 토큰 및 쿠키 연결 수정 및 oauth 구조 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/enums/ErrorCode.java
src/main/java/com/daengdaeng_eodiga/project/Global/exception/BannerNotFoundException.java
src/main/java/com/daengdaeng_eodiga/project/banner/controller/BannerController.java
src/main/java/com/daengdaeng_eodiga/project/banner/dto/BannerDetailDto.java
src/main/java/com/daengdaeng_eodiga/project/banner/dto/BannerListDto.java
src/main/java/com/daengdaeng_eodiga/project/banner/service/BannerService.java
src/main/java/com/daengdaeng_eodiga/project/event/entity/Event.java
src/main/java/com/daengdaeng_eodiga/project/event/repository/EventRepository.java
src/main/java/com/daengdaeng_eodiga/project/place/repository/PlaceRepository.java

> 1. 배너 메인 목록 조회
> 이벤트 db로부터 오늘 날짜 기준으로 기간내에 있는 이벤트 목록 리스트 조회
> 2. 배너 클릭 시 이벤트 상세 조회
> 1. 배너 목록 조회
> 2. 배너 상세 조회

Feat/banner: 배너 API 구현

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAccessDeniedHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomOAuth2UserService.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/TokenService.java

Refator/jwt :도메인간 쿠키 연결

---

build.gradle
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

refator/jwt:쿠키 도메인 간 추가 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java

refator/jwt:쿠키 요소 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

Refator/jwt: 토큰 요소 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

v1:토큰 요소 수정

---

build.gradle
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java
src/main/resources/static/signupPage.html

refator:쿠키 요소 ,시큐리티 수정

---

build.gradle
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTUtil.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java
src/main/resources/static/signupPage.html

v1:쿠키 요소 ,시큐리티 수정

---

src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java

refator/jwt:oauth 컨트롤러 url수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomSuccessHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/TokenService.java

refator/jwt:테스트를 위한 임시 헤더 추가

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

refator/jwt:테스트를 위한 시큐리티 체크

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

refator/jwt:"시큐리티 파비콘 허용

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

v1:시큐리티 경로 허용 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationFailureHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

refator/jwt:시큐리티 핸들러 변경

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationFailureHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

v1: 시큐리티 핸들러 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

Refator/jwt: 시큐리티 허용 변경

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationFailureHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

v1:시큐리티 허용 변경

---

src/main/java/com/daengdaeng_eodiga/project/oauth/service/OauthUserService.java

v1:setOauthProvider 추가

---

src/main/java/com/daengdaeng_eodiga/project/Global/Geo/Service/GeoService.java
src/main/java/com/daengdaeng_eodiga/project/Global/Geo/dto/KakaoApiProperties.java
src/main/java/com/daengdaeng_eodiga/project/Global/Geo/dto/KakaoApiResponseDto.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/OauthUserService.java
src/main/java/com/daengdaeng_eodiga/project/place/controller/PlaceController.java
src/main/java/com/daengdaeng_eodiga/project/place/service/PlaceService.java

Refator/recommend place: ouath 서비스,카카오 api 수정

---

src/main/java/com/daengdaeng_eodiga/project/place/controller/PlaceController.java
src/main/java/com/daengdaeng_eodiga/project/place/repository/PlaceRepository.java
src/main/java/com/daengdaeng_eodiga/project/place/service/PlaceService.java

1. 검색기능 이용시 즐겨찾기 여부가 항상 false로 반환되는 오류 수정.

refactor: 검색기능버그수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomSuccessHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/java/com/daengdaeng_eodiga/project/Global/config/WebConfig.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java

- 도메인간 쿠키 공유를 위해 Cookie 대신 ResponseCookie 적용
- 프론트 테스트를 위해 localhost CORS 허용

Refactor/security cors  ResponseCookie 적용 및 전역 CORS 설정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Geo/Service/GeoService.java
src/main/java/com/daengdaeng_eodiga/project/Global/Geo/dto/KakaoApiResponseDto.java
src/main/java/com/daengdaeng_eodiga/project/Global/controller/RollingController.java
src/main/java/com/daengdaeng_eodiga/project/place/controller/PlaceController.java
src/main/java/com/daengdaeng_eodiga/project/place/service/PlaceService.java

사용자 동의 안했을 시 사용자 시,도 기준으로 좌표 가져오기

refator:사용자 동의 안했을 시 사용자 시,도 기준으로 좌표 가져오기

---

src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java
src/main/java/com/daengdaeng_eodiga/project/oauth/service/TokenService.java

- 기존에 응답값을 response로 전달해주는 문제가 있었으나, null로 수정했습니다

V1 : signup  응답값 null로 수정

---

.github/workflows/deploy.yml
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/JWTFilter.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java
src/main/resources/application.yml

- 프론트 로컬에서 테스트 하는 경우 고정된 유저로 조회

V1 : 테스트 모드 추가

---

src/main/java/com/daengdaeng_eodiga/project/favorite/dto/FavoriteResponseDto.java
src/main/java/com/daengdaeng_eodiga/project/favorite/service/FavoriteService.java
src/main/java/com/daengdaeng_eodiga/project/place/entity/Place.java
src/main/java/com/daengdaeng_eodiga/project/place/entity/PlaceMedia.java
src/main/java/com/daengdaeng_eodiga/project/place/repository/PlaceMediaRepository.java

> 즐겨찾기 목록 조회 시, 장소이미지와 장소타입을 함께 반환하도록 수정
> ![image](https://github.com/user-attachments/assets/8d74f62a-b761-41d9-ba8d-3be09073c1cf)

Refactor/Favorite: 즐겨찾기 목록 조회 시, 장소이미지와 장소타입을 함께 반환하도록 수정

---

src/main/java/com/daengdaeng_eodiga/project/preference/repository/PreferenceRepository.java
src/main/java/com/daengdaeng_eodiga/project/preference/service/PreferenceService.java

> 선호도 중복 등록 예외 수정
> 유저 + 선호도 그룹코드 기준으로 중복 검사

refactor/preference: 선호도 중복 등록 예외 수정

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomOAuth2UserService.java
src/main/java/com/daengdaeng_eodiga/project/ProjectApplication.java
src/main/java/com/daengdaeng_eodiga/project/pet/entity/Pet.java
src/main/java/com/daengdaeng_eodiga/project/place/entity/Place.java
src/main/java/com/daengdaeng_eodiga/project/place/service/PlaceService.java
src/main/java/com/daengdaeng_eodiga/project/review/entity/Review.java
src/main/java/com/daengdaeng_eodiga/project/user/config/UserJobConfig.java
src/main/java/com/daengdaeng_eodiga/project/user/config/UserScheduler.java
src/main/java/com/daengdaeng_eodiga/project/user/entity/User.java
src/main/resources/application.yml

- 회원탈퇴를 요청한 후, 30일이 지난 유저는 물리적 삭제를 진행한다.
- 만약 oath 로그인을 진행했는데, 탈퇴를 요청한 유저라면 409예외가 발생한다.

Refactor/delete user : 회원탈퇴 물리적 삭제 배치 구현

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationEntryPoint.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationFailureHandler.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomOAuth2UserService.java
src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/SecurityConfig.java

- 탈퇴한 유저가 30일 이내 로그인시, 409 예외를 전달합니다.

Refactor/delete user : 회원탈퇴 유저 예외처리

---

src/main/java/com/daengdaeng_eodiga/project/Global/Security/config/CustomAuthenticationFailureHandler.java
src/main/java/com/daengdaeng_eodiga/project/oauth/controller/OuathController.java

유저 탈퇴시, 리다이렉트되는 메서드 controller로 추출

V1 : 유저 탈퇴 리다이렉트 메서드 controller로 추출
